import Head from 'next/head'
import useFirebase from '../components/Login/Firebase/useFirebase';
import styles from '../styles/Home.module.css'
import { useSelector } from 'react-redux';
import NavigationBar from '../components/Home/NavigationBar/NavigationBar';
import Header from '../components/Home/Header/Header';
import Products from '../components/Home/Products/Products';


export default function Home() {
  const { signInWithGoogle, logOut, loading } = useFirebase();
  const { user, authLoading } = useSelector(state => state.auth);

  console.log("This is logged in user", user);


  return (
    <div className={styles.container}>
      <Head>
        <title>Bit Brothers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <NavigationBar />
        {/* <Header /> */}
        {/* <Products /> */}

      </main>
    </div>
  )
}
