import Head from 'next/head'
import styles from '../styles/Home.module.css'
import NavigationBar from '../components/Home/NavigationBar/NavigationBar';
import Header from '../components/Home/Header/Header';
import Products from '../components/Home/Products/Products';
import axios from 'axios';
import Footer from '../components/Home/Footer/Footer';

export default function Home({ productsData }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Bit Brothers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <NavigationBar />
                <Header />
                <div className='max-w-[1280px] mx-auto'>
                    <Products productsData={productsData} />
                </div>
                <Footer />

            </main>
        </div>
    )
}

// export const getStaticProps = async () => {
//     const res = await axios.get(`http://localhost:3000/api/products`);
//     return {
//         props: {
//             productsData: res.data,
//         },
//         revalidate: 10
//     };
// };