import Head from 'next/head'
import useFirebase from '../components/Login/Firebase/useFirebase';
import styles from '../styles/Home.module.css'
import { useSelector } from 'react-redux';
import NavigationBar from '../components/Home/NavigationBar/NavigationBar';
import Header from '../components/Home/Header/Header';
import Products from '../components/Home/Products/Products';
import axios from 'axios';


export default function Home({ productsData }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>Bit Brothers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="">
                <NavigationBar />
                <Header />
                <div className='max-w-[1280px] mx-auto'>
                    <Products productsData={productsData} />
                </div>

            </main>
        </div>
    )
}

export const getStaticProps = async () => {
    const res = await axios.get(`/api/products`);
    return {
        props: {
            productsData: res.data,
        },
        revalidate: 10
    };
};